// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ops", "SalesOrderLine")]
    [Int32Column("SalesOrderLineId", Pk = true, Identity = true)]
    [Int32Column("SalesOrderId", FkTable = "SalesOrder", FkColumn = "SalesOrderId")]
    [Int32Column("LineNumber")]
    [Int32Column("ProductId", FkSchema = "ref", FkTable = "Product", FkColumn = "ProductId")]
    [Int32Column("WarehouseId", FkSchema = "ref", FkTable = "Warehouse", FkColumn = "WarehouseId")]
    [Int32Column("Quantity")]
    [DecimalColumn("UnitPrice", Precision = 12, Scale = 2)]
    [DecimalColumn("DiscountPercent", Precision = 5, Scale = 2, DefaultValue = "0")]
    [StringColumn("LineStatus", Unicode = true, MaxLength = 20, DefaultValue = "Open")]
    [Index("SalesOrderId", "LineNumber", Unique = true)]
    [Index("ProductId")]
    [Index("WarehouseId")]
    public partial class TableSalesOrderLine
    {
    }
}