// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace SqDbAiAgent.ConsoleApp.Tables
{
    [TableDescriptor("dbo", "sysdiagrams")]
    [Int32Column("diagram_id", PropertyName = "DiagramId", Pk = true, Identity = true)]
    [StringColumn("name", Unicode = true, MaxLength = 128)]
    [Int32Column("principal_id", PropertyName = "PrincipalId")]
    [NullableInt32Column("version")]
    [NullableByteArrayColumn("definition")]
    [Index("principal_id", "name", Unique = true)]
    public partial class TableSysdiagrams
    {
    }
}