// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ops", "Shipment")]
    [Int32Column("ShipmentId", Pk = true, Identity = true)]
    [StringColumn("ShipmentNumber", Unicode = true, MaxLength = 20)]
    [Int32Column("SalesOrderId", FkTable = "SalesOrder", FkColumn = "SalesOrderId")]
    [Int32Column("WarehouseId", FkSchema = "ref", FkTable = "Warehouse", FkColumn = "WarehouseId")]
    [DateTimeColumn("ShipmentDate", IsDate = true)]
    [StringColumn("CarrierName", Unicode = true, MaxLength = 80)]
    [NullableStringColumn("TrackingNumber", Unicode = true, MaxLength = 50)]
    [StringColumn("ShipmentStatus", Unicode = true, MaxLength = 20)]
    [Index("ShipmentNumber", Unique = true)]
    [Index("SalesOrderId")]
    public partial class TableShipment
    {
    }
}