// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("sec", "AppRole")]
    [Int32Column("AppRoleId", Pk = true, Identity = true)]
    [StringColumn("RoleName", Unicode = true, MaxLength = 50)]
    [NullableStringColumn("Description", Unicode = true, MaxLength = 200)]
    [Index("RoleName", Unique = true)]
    public partial class TableAppRole
    {
    }
}
