// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("sec", "AuditLog")]
    [Int64Column("AuditLogId", Pk = true, Identity = true)]
    [Int32Column("AppUserId", FkTable = "AppUser", FkColumn = "AppUserId")]
    [DateTimeColumn("EventUtc", DefaultValue = "$utcNow")]
    [StringColumn("EventType", Unicode = true, MaxLength = 40)]
    [StringColumn("EntityName", Unicode = true, MaxLength = 80)]
    [StringColumn("EntityId", Unicode = true, MaxLength = 80)]
    [NullableStringColumn("Details", Unicode = true, MaxLength = 400)]
    [Index("AppUserId", "EventUtc")]
    public partial class TableAuditLog
    {
    }
}