// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ops", "SalesOrder")]
    [Int32Column("SalesOrderId", Pk = true, Identity = true)]
    [StringColumn("OrderNumber", Unicode = true, MaxLength = 20)]
    [Int32Column("BranchId", FkSchema = "ref", FkTable = "Branch", FkColumn = "BranchId")]
    [Int32Column("CustomerId", FkSchema = "ref", FkTable = "Customer", FkColumn = "CustomerId")]
    [Int32Column("SalesRepId", FkSchema = "ref", FkTable = "Employee", FkColumn = "EmployeeId")]
    [StringColumn("OrderStatus", Unicode = true, MaxLength = 20)]
    [DateTimeColumn("OrderDate", IsDate = true)]
    [NullableDateTimeColumn("RequiredDate", IsDate = true)]
    [StringColumn("CurrencyCode", MaxLength = 3, FixedLength = true, DefaultValue = "CAD")]
    [NullableStringColumn("Notes", Unicode = true, MaxLength = 200)]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [Index("OrderNumber", Unique = true)]
    [Index("BranchId", "OrderDate")]
    [Index("SalesRepId")]
    [Index("OrderStatus")]
    [Index("CustomerId", "OrderDate")]
    public partial class TableSalesOrder
    {
    }
}