// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ops", "Payment")]
    [Int32Column("PaymentId", Pk = true, Identity = true)]
    [Int32Column("InvoiceId", FkTable = "Invoice", FkColumn = "InvoiceId")]
    [DateTimeColumn("PaymentDate", IsDate = true)]
    [StringColumn("PaymentMethod", Unicode = true, MaxLength = 20)]
    [DecimalColumn("Amount", Precision = 12, Scale = 2)]
    [NullableStringColumn("ReferenceNumber", Unicode = true, MaxLength = 40)]
    [Index("InvoiceId")]
    public partial class TablePayment
    {
    }
}