// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("sec", "UserWarehouseAccess")]
    [Int32Column("AppUserId", Pk = true, FkTable = "AppUser", FkColumn = "AppUserId")]
    [Int32Column("WarehouseId", Pk = true, FkSchema = "ref", FkTable = "Warehouse", FkColumn = "WarehouseId")]
    [BooleanColumn("CanRead")]
    [BooleanColumn("CanWrite")]
    [Index("WarehouseId")]
    public partial class TableUserWarehouseAccess
    {
    }
}