// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ref", "Product")]
    [Int32Column("ProductId", Pk = true, Identity = true)]
    [Int32Column("ProductCategoryId", FkTable = "ProductCategory", FkColumn = "ProductCategoryId")]
    [StringColumn("Sku", Unicode = true, MaxLength = 30)]
    [StringColumn("ProductName", Unicode = true, MaxLength = 120)]
    [DecimalColumn("UnitPrice", Precision = 12, Scale = 2)]
    [DecimalColumn("UnitCost", Precision = 12, Scale = 2)]
    [BooleanColumn("IsDiscontinued", DefaultValue = "0")]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [Index("Sku", Unique = true)]
    [Index("ProductCategoryId")]
    [Index("ProductName")]
    public partial class TableProduct
    {
    }
}