// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ref", "Branch")]
    [Int32Column("BranchId", Pk = true, Identity = true)]
    [StringColumn("BranchCode", Unicode = true, MaxLength = 12)]
    [StringColumn("BranchName", Unicode = true, MaxLength = 100)]
    [StringColumn("Region", Unicode = true, MaxLength = 50)]
    [StringColumn("City", Unicode = true, MaxLength = 50)]
    [BooleanColumn("IsActive", DefaultValue = "1")]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [Index("BranchCode", Unique = true)]
    public partial class TableBranch
    {
    }
}