// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ops", "ShipmentLine")]
    [Int32Column("ShipmentLineId", Pk = true, Identity = true)]
    [Int32Column("ShipmentId", FkTable = "Shipment", FkColumn = "ShipmentId")]
    [Int32Column("SalesOrderLineId", FkTable = "SalesOrderLine", FkColumn = "SalesOrderLineId")]
    [Int32Column("QuantityShipped")]
    [Index("ShipmentId", "SalesOrderLineId", Unique = true)]
    public partial class TableShipmentLine
    {
    }
}