// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ref", "ProductCategory")]
    [Int32Column("ProductCategoryId", Pk = true, Identity = true)]
    [StringColumn("CategoryCode", Unicode = true, MaxLength = 20)]
    [StringColumn("CategoryName", Unicode = true, MaxLength = 80)]
    [BooleanColumn("IsActive", DefaultValue = "1")]
    [Index("CategoryCode", Unique = true)]
    public partial class TableProductCategory
    {
    }
}