// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ref", "Customer")]
    [Int32Column("CustomerId", Pk = true, Identity = true)]
    [Int32Column("BranchId", FkTable = "Branch", FkColumn = "BranchId")]
    [StringColumn("CustomerCode", Unicode = true, MaxLength = 20)]
    [StringColumn("CustomerName", Unicode = true, MaxLength = 120)]
    [StringColumn("CustomerType", Unicode = true, MaxLength = 20)]
    [StringColumn("City", Unicode = true, MaxLength = 50)]
    [StringColumn("Province", Unicode = true, MaxLength = 50)]
    [DecimalColumn("CreditLimit", Precision = 12, Scale = 2)]
    [BooleanColumn("IsActive", DefaultValue = "1")]
    [NullableInt32Column("PreferredWarehouseId", FkTable = "Warehouse", FkColumn = "WarehouseId")]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [Index("CustomerCode", Unique = true)]
    [Index("BranchId")]
    [Index("CustomerName")]
    public partial class TableCustomer
    {
    }
}