// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("sec", "UserBranchAccess")]
    [Int32Column("AppUserId", Pk = true, FkTable = "AppUser", FkColumn = "AppUserId")]
    [Int32Column("BranchId", Pk = true, FkSchema = "ref", FkTable = "Branch", FkColumn = "BranchId")]
    [BooleanColumn("CanRead")]
    [BooleanColumn("CanWrite")]
    [Index("BranchId")]
    public partial class TableUserBranchAccess
    {
    }
}