// <auto-generated/>
#nullable enable
using SqExpress.TableDecalationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("sec", "AppUser")]
    [Int32Column("AppUserId", Pk = true, Identity = true)]
    [StringColumn("LoginName", Unicode = true, MaxLength = 50)]
    [StringColumn("DisplayName", Unicode = true, MaxLength = 100)]
    [NullableInt32Column("EmployeeId", FkSchema = "ref", FkTable = "Employee", FkColumn = "EmployeeId")]
    [BooleanColumn("IsActive", DefaultValue = "1")]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [Index("LoginName", Unique = true)]
    public partial class TableAppUser
    {
    }
}