// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("sec", "UserRole")]
    [Int32Column("AppUserId", Pk = true, FkTable = "AppUser", FkColumn = "AppUserId")]
    [Int32Column("AppRoleId", Pk = true, FkTable = "AppRole", FkColumn = "AppRoleId")]
    [DateTimeColumn("GrantedUtc", DefaultValue = "$utcNow")]
    public partial class TableUserRole
    {
    }
}