// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("sec", "UserCustomerAccess")]
    [Int32Column("AppUserId", Pk = true, FkTable = "AppUser", FkColumn = "AppUserId")]
    [Int32Column("CustomerId", Pk = true, FkSchema = "ref", FkTable = "Customer", FkColumn = "CustomerId")]
    [BooleanColumn("CanRead")]
    [BooleanColumn("CanWrite")]
    [Index("CustomerId")]
    public partial class TableUserCustomerAccess
    {
    }
}