// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ref", "Warehouse")]
    [Int32Column("WarehouseId", Pk = true, Identity = true)]
    [Int32Column("BranchId", FkTable = "Branch", FkColumn = "BranchId")]
    [StringColumn("WarehouseCode", Unicode = true, MaxLength = 20)]
    [StringColumn("WarehouseName", Unicode = true, MaxLength = 100)]
    [StringColumn("City", Unicode = true, MaxLength = 50)]
    [BooleanColumn("IsPrimary", DefaultValue = "0")]
    [BooleanColumn("IsActive", DefaultValue = "1")]
    [Index("WarehouseCode", Unique = true)]
    [Index("BranchId")]
    public partial class TableWarehouse
    {
    }
}