// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ref", "InventoryBalance")]
    [Int32Column("WarehouseId", Pk = true, FkTable = "Warehouse", FkColumn = "WarehouseId")]
    [Int32Column("ProductId", Pk = true, FkTable = "Product", FkColumn = "ProductId")]
    [Int32Column("QuantityOnHand")]
    [Int32Column("QuantityReserved")]
    [Int32Column("ReorderLevel")]
    [DateTimeColumn("LastCountedUtc")]
    [Index("ProductId")]
    public partial class TableInventoryBalance
    {
    }
}