// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ops", "Invoice")]
    [Int32Column("InvoiceId", Pk = true, Identity = true)]
    [StringColumn("InvoiceNumber", Unicode = true, MaxLength = 20)]
    [Int32Column("SalesOrderId", FkTable = "SalesOrder", FkColumn = "SalesOrderId")]
    [DateTimeColumn("InvoiceDate", IsDate = true)]
    [StringColumn("InvoiceStatus", Unicode = true, MaxLength = 20)]
    [DecimalColumn("SubtotalAmount", Precision = 12, Scale = 2)]
    [DecimalColumn("TaxAmount", Precision = 12, Scale = 2)]
    [DecimalColumn("TotalAmount", Precision = 12, Scale = 2)]
    [DateTimeColumn("DueDate", IsDate = true)]
    [Index("InvoiceNumber", Unique = true)]
    [Index("SalesOrderId")]
    [Index("InvoiceStatus", "DueDate")]
    public partial class TableInvoice
    {
    }
}