// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace AiDbClient.ConsoleApp.Tables
{
    [TableDescriptor("ref", "Employee")]
    [Int32Column("EmployeeId", Pk = true, Identity = true)]
    [Int32Column("BranchId", FkTable = "Branch", FkColumn = "BranchId")]
    [StringColumn("EmployeeCode", Unicode = true, MaxLength = 20)]
    [StringColumn("FirstName", Unicode = true, MaxLength = 50)]
    [StringColumn("LastName", Unicode = true, MaxLength = 50)]
    [StringColumn("Title", Unicode = true, MaxLength = 80)]
    [StringColumn("Email", Unicode = true, MaxLength = 120)]
    [BooleanColumn("IsSalesRep", DefaultValue = "0")]
    [BooleanColumn("IsActive", DefaultValue = "1")]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [Index("Email", Unique = true)]
    [Index("EmployeeCode", Unique = true)]
    [Index("BranchId")]
    public partial class TableEmployee
    {
    }
}